authentication:
  allow_anonymous_access: True
  single_user_api_key: mykey

allow_origins:
  - '*'

qserver_zmq_configuration:
  control_address: tcp://re-manager:60615
  info_address: tcp://re-manager:60625


api_access:
  policy: bluesky_httpserver.authorization:BasicAPIAccessControl
  args:
    roles:
      unauthenticated_public:
        scopes_add:
          - write:manager:control
          - write:queue:control
          - read:resources
          - write:queue:edit
          - read:console
          - read:queue
          - read:status
          - write:queue
          - write:execute
          - read:history
      unauthenticated_single_user:
        scopes_add:
          - write:manager:control
          - read:console
          - read:queue
          - read:history
          - write:queue:edit
          - read:status
          - write:queue
          - write:scripts
          - user:apikeys
